# Generated by Django 4.0.4 on 2022-05-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='choice',
            name='recent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.BooleanField(default=False),
        ),
    ]
